; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: library dependencies, extra library storages
;   Advanced options: extra scripting
; https://docs.platformio.org/page/projectconf.html

[env:teensy41]
platform = teensy
board = teensy41
framework = arduino
build_type = release
build_unflags = -fexceptions
build_flags =
    -DFWVERSION=0.1
    -fno-exceptions
    -DPlatformTeensy
    -DWD_EXPIRE=2 ; 2 sec
    -DENABLE_WD ; DISABLE_WD for debug
    -DLOGGER_SIZE=256
    -DLoggerSerialDev=Serial1
    -DSERIAL_BAUDRATE=115200
    -D_TASK_STD_FUNCTION
    -D_TASK_MICRO_RES
    -DUSB_DUAL_SERIAL
    -DCmdSerialDev=Serial
    -DWATCHDOG_LED=13
    -DPROMT=\"mnptester$\ \"
    -Iinclude
    -I.pio/libdeps/teensy41/TaskScheduler/src
    -I.pio/libdeps/teensy41/FastCRC/src
    -I.pio/libdeps/teensy41/NativeEthernet/src
    -I/home/lenel/.platformio/packages/framework-arduinoteensy/libraries/FNET/src
    -I.pio/libdeps/teensy41/CmdArduino
    -I.pio/libdeps/teensy41/SimpleEvents/include
    -I.pio/libdeps/teensy41/loggingLib

build_src_filter =
    +<*>
    -<board/persistent.cpp>

monitor_speed = 115200
lib_deps =
    arkhipenko/TaskScheduler
    bblanchon/ArduinoJson @ ^7.4.3
    https://github.com/FrankBoesing/FastCRC.git#c669a89
    https://github.com/vjmuzik/NativeEthernet.git
    https://github.com/SMFSW/Queue#6bd9a4e
    https://github.com/tonton81/WDT_T4#1910b57
    https://github.com/jnk0le/Ring-Buffer.git#160190e
    https://github.com/lbuchman/CmdArduino.git
    https://github.com/lbuchman/loggingLib.git
    https://github.com/lbuchman/SimpleEvents.git#37aef6a
